### ISSUE TITLE
Wilson changes

### ISSUE THREAD

**Issue by JayLil07** [darionco/Warsak#10]
Wison is one of the few characters we haven't changed yet. Our plan for him is to be a well rounded character. You would play him when you don't know what other character would fit in your team, or if you're new and don't want a character too different from the base game. What is well rounded, you ask? Well, we don't know...

**Comment by darionco** [comment]
We decided to make wilson get more powerful the longer he stays alive and the more enemies he kills. This aligns with the bounty system, so when the bounty system is in place we can make this change happen by tying Wilson's current power to his bounty. His beard will also show how powerful he is.

Switching to `blocked` since this can't be worked on until the bounty system is ready.

**Comment by darionco** [comment]
Done, needs testing.
