### ISSUE TITLE
Webber nerf

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#29]
Webber needs a limit to how many spiders he can tame at once. It holds makes the entire game up, and can make games go way too long

Webber can also tame the dangling depth dweller in the boss rush, take it out the wormhole, and use deerclops to destroy the enemy base

**Comment by JayLil07** [comment]
An idea we have is to make Webber unable to tame spiders, but be able to craft a spiderhat. This can make him only be able to have 10 or so followers at a time. The hat only lasts for 2 minutes, and can attract enemy spiders (tamed spiders from your team will start attacking them), making the hat have a few downsides as well.

**Comment by Thisguyizbad** [comment]
the issue of taking the depth dweller still persists after the spiderhat is implemented

**Comment by darionco** [comment]
yeah, but adding the spiderhat would mean that only one spider type needs to be patched to not accept webber's food, instead of having to create a custom spider taming system for webber.

The final fix would be to remove webbers ability to tame spiders, allow him to craft the spider hat and patch the depth dweller spider to not accept food from anyone

**Comment by Thisguyizbad** [comment]
sounds good!

**Comment by darionco** [comment]
fixed
