### ISSUE TITLE
change character descriptions

### ISSUE THREAD

**Issue by Thisguyizbad** [darionco/Warsak#33]
many of the descriptions are innacurate or wrong, here is what I have so far:

1. Walter has a bee allergy
2. Wolfgang has a damage multiplier and can actually become weaker when at low hunger
3. Wortox has 1/2 the normal nutritional value from foods
4. Wilson's life-force-stealing stubble doesn't have anything to do with killing people
5."Will beat you in hockey" you guys mentioned it being a requirement in the code, I'm not sure how to fix tho
6. Not sure if Warly can/cannot eat non-crockpot food
7. Wormwood can't heal normally but can still use jellybeans i think
8. Wendy is still WIP 
9. What is Wigfrid's ability? Craft spears n' helmets? No!
10. Webber could befriend spiders

**Comment by darionco** [comment]
@JayLil07 updated the descriptions yesterday, maybe you two can discuss?
You can see the new descriptions in the staging server or here:
https://github.com/darionco/Warsak/blob/main/mod/scripts/init/character_descriptions.lua

**Comment by Thisguyizbad** [comment]
wick's desc needs to be updated as well

**Comment by JayLil07** [comment]
**Walter:** - Get a slingshot from the shop - Ammo can be bought too - Has a bee allergy
**Wolfgang:** Shouldn't have a damage multiplier
**Wortox:** - Souls drop by last hitting enemy players - Also beehives and pigs - Cannot soulhop when wearing the piggyback - Gets less hunger and health from food
**Wilson:** NEWEST CHARACTER RELEASE - Uses your life force to grow his stubble (will be released next update so no need to remove it)
**Woodie (us only):** - Can transform into the weremoose - Will beat thisguyizgood at hockey
**Warly:** - Can build a seasoning station - Crafts spices - Why not add some flavor to food?! - Can only eat crockpot meals
**Wormwood:** - Can craft bramble items - And compost wrap - Cannot heal from food - With the exception of jellybeans
**Wendy:** Not really needed since every character is a work in progress and needs balancing
**Wigfrid:** Already kind of op since she heals every few hits and has extra absorption and damage, so I don't think she needs any custom crafting recipes
**Webber:** - Can be played as a tank - Takes less damage from spiders - Can craft a spiderhat (should be fixed in the next update)
**Wickerbottom:** - Can craft Heart Tart Art - Can also craft Humpty Dumpty

**Comment by Thisguyizbad** [comment]
pretty sure this one is done, at least the descriptions listed are
